"""add chat threads and messages

Revision ID: 065beb2912a0
Revises: f9e3f7a938ad
Create Date: 2026-07-16 09:47:06.699945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '065beb2912a0'
down_revision: Union[str, Sequence[str], None] = 'f9e3f7a938ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='chat_thread_status'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('subject', sa.Enum('policy', 'order', 'refund', 'membership', 'general', name='chat_subject'), server_default=sa.text("'general'"), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_threads_last_message_at', 'chat_threads', ['last_message_at'], unique=False)
    op.create_index('ix_chat_threads_user_id_status', 'chat_threads', ['user_id', 'status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='chat_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='chat_message_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("length(regexp_replace(content, '[[:space:]]', '', 'g')) > 0", name='ck_chat_messages_content_not_blank'),
    sa.CheckConstraint('sequence_number > 0', name='ck_chat_messages_sequence_number_positive'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'sequence_number', name='uq_chat_messages_thread_id_sequence_number')
    )
    op.create_index('ix_chat_messages_thread_id_created_at', 'chat_messages', ['thread_id', 'created_at'], unique=False)
    op.create_index('ix_chat_messages_trace_id', 'chat_messages', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        "ix_chat_messages_trace_id",
        table_name="chat_messages",
    )
    op.drop_index(
        "ix_chat_messages_thread_id_created_at",
        table_name="chat_messages",
    )
    op.drop_table("chat_messages")

    op.drop_index(
        "ix_chat_threads_user_id_status",
        table_name="chat_threads",
    )
    op.drop_index(
        "ix_chat_threads_last_message_at",
        table_name="chat_threads",
    )
    op.drop_table("chat_threads")

    op.execute(
        "DROP TYPE IF EXISTS chat_message_status"
    )
    op.execute(
        "DROP TYPE IF EXISTS chat_message_role"
    )
    op.execute(
        "DROP TYPE IF EXISTS chat_subject"
    )
    op.execute(
        "DROP TYPE IF EXISTS chat_thread_status"
    )