"""add agent runs and audit logs

Revision ID: 72835e40a398
Revises: 065beb2912a0
Create Date: 2026-07-17 04:50:32.815491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72835e40a398'
down_revision: Union[str, Sequence[str], None] = '065beb2912a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'agent', 'system', 'admin', name='audit_actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Enum('success', 'failure', 'denied', 'pending', name='audit_result'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_type_actor_id', 'audit_logs', ['actor_type', 'actor_id'], unique=False)
    op.create_index('ix_audit_logs_resource_type_resource_id', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_trace_id_created_at', 'audit_logs', ['trace_id', 'created_at'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='agent_run_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('intent', sa.String(length=128), nullable=True),
    sa.Column('workflow_version', sa.String(length=64), server_default=sa.text("'0.1.0'"), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name='ck_agent_runs_duration_non_negative'),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name='ck_agent_runs_input_tokens_non_negative'),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name='ck_agent_runs_output_tokens_non_negative'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id', name='uq_agent_runs_trace_id')
    )
    op.create_index('ix_agent_runs_status_created_at', 'agent_runs', ['status', 'created_at'], unique=False)
    op.create_index('ix_agent_runs_thread_id_created_at', 'agent_runs', ['thread_id', 'created_at'], unique=False)
    op.create_table('agent_node_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=128), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', name='agent_node_run_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name='ck_agent_node_runs_duration_non_negative'),
    sa.CheckConstraint('sequence_number > 0', name='ck_agent_node_runs_sequence_number_positive'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'sequence_number', name='uq_agent_node_runs_run_id_sequence_number')
    )
    op.create_index('ix_agent_node_runs_agent_run_id_status', 'agent_node_runs', ['agent_run_id', 'status'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('node_run_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'timeout', name='tool_call_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name='ck_tool_calls_duration_non_negative'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_run_id'], ['agent_node_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_calls_agent_run_id_status', 'tool_calls', ['agent_run_id', 'status'], unique=False)
    op.create_index('ix_tool_calls_tool_name_created_at', 'tool_calls', ['tool_name', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        "ix_tool_calls_tool_name_created_at",
        table_name="tool_calls",
    )
    op.drop_index(
        "ix_tool_calls_agent_run_id_status",
        table_name="tool_calls",
    )
    op.drop_table("tool_calls")

    op.drop_index(
        "ix_agent_node_runs_agent_run_id_status",
        table_name="agent_node_runs",
    )
    op.drop_table("agent_node_runs")

    op.drop_index(
        "ix_agent_runs_thread_id_created_at",
        table_name="agent_runs",
    )
    op.drop_index(
        "ix_agent_runs_status_created_at",
        table_name="agent_runs",
    )
    op.drop_table("agent_runs")

    op.drop_index(
        "ix_audit_logs_trace_id_created_at",
        table_name="audit_logs",
    )
    op.drop_index(
        "ix_audit_logs_resource_type_resource_id",
        table_name="audit_logs",
    )
    op.drop_index(
        "ix_audit_logs_actor_type_actor_id",
        table_name="audit_logs",
    )
    op.drop_table("audit_logs")

    op.execute(
        "DROP TYPE IF EXISTS tool_call_status"
    )
    op.execute(
        "DROP TYPE IF EXISTS agent_node_run_status"
    )
    op.execute(
        "DROP TYPE IF EXISTS agent_run_status"
    )
    op.execute(
        "DROP TYPE IF EXISTS audit_result"
    )
    op.execute(
        "DROP TYPE IF EXISTS audit_actor_type"
    )