"""add document chunks

Revision ID: e010caf2d41b
Revises: 0d5401da8f2c
Create Date: 2026-07-16 04:23:50.707764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e010caf2d41b'
down_revision: Union[str, Sequence[str], None] = '0d5401da8f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='ck_document_chunks_chunk_index_non_negative'),
    sa.CheckConstraint('length(trim(content)) > 0', name='ck_document_chunks_content_not_blank'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'chunk_index', name='uq_document_chunks_version_id_chunk_index')
    )
    op.create_index('ix_document_chunks_content_hash', 'document_chunks', ['content_hash'], unique=False)
    op.create_index('ix_document_chunks_document_version_id_chunk_index', 'document_chunks', ['document_version_id', 'chunk_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_document_version_id_chunk_index', table_name='document_chunks')
    op.drop_index('ix_document_chunks_content_hash', table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
